name: CI

on:
  push:
    branches: [ master, main ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  Execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-major-version: [ 3 ]
        python-minor-version: [ 7, 8, 9, 10, 11 ]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ format('{0}.{1}', matrix.python-major-version, matrix.python-minor-version) }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --upgrade coveralls
          pip3 install -e .[dev]

      - name: Run checks
        run: |
          python3 precommit.py

      - name: Upload Coverage
        # Python 3.7 has problems with coverage.
        if: ${{ matrix.python-minor-version > 7 }}
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true

  Finish-Coveralls:
    name: Finish Coveralls
    needs: Execute
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finish Coveralls
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
